on: 
  pull_request:
    branches:
      - staging
    types: 
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Create pr
        run: gh pr create -B "main" -t "deploy to prod" -b "This is body."

