name: Get ref on pull request
on:
  pull_request:
    branches:
      - main

jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo sha
        id: make-comments
        env:
          SHA: ${{ github.sha }}
        run: |
          comments=/tmp/comments.txt
          echo "# Diff1" > ${comments}
          echo $SHA | tee -a ${comments}
          echo "# Diff2" >> ${comments}
          echo $GITHUB_REF | tee -a ${comments}
          echo ::set-output name=result::${comments}
      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ${{ steps.make-comments.outputs.result }} "${URL}"
