name: Sha test tag
on:
  release:
    types: [published]

jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo sha
        env:
          SHA: ${{ github.sha }}
        run: |
          echo $SHA
          echo $GITHUB_REF
